// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFG2nJt0hQ_NBIwEMIUNynW4D7_9mMBA',
    appId: '1:400781427180:web:6adcf9d68cc0b9743040c9',
    messagingSenderId: '400781427180',
    projectId: 'remoteconfigtrial-f912f',
    authDomain: 'remoteconfigtrial-f912f.firebaseapp.com',
    storageBucket: 'remoteconfigtrial-f912f.appspot.com',
    measurementId: 'G-ZFNMPPFRTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvgU7SKuf-5XAVXPXpUzIOJ534p7P9DA',
    appId: '1:400781427180:android:704507894a7ac5b23040c9',
    messagingSenderId: '400781427180',
    projectId: 'remoteconfigtrial-f912f',
    storageBucket: 'remoteconfigtrial-f912f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqFAaveeQ17Qc7cyZM0o-LISRv1QbIhLs',
    appId: '1:400781427180:ios:e511bfb0950dd1e53040c9',
    messagingSenderId: '400781427180',
    projectId: 'remoteconfigtrial-f912f',
    storageBucket: 'remoteconfigtrial-f912f.appspot.com',
    iosBundleId: 'com.example.firebaseRemoteConfigApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqFAaveeQ17Qc7cyZM0o-LISRv1QbIhLs',
    appId: '1:400781427180:ios:f22cf91f6faff7173040c9',
    messagingSenderId: '400781427180',
    projectId: 'remoteconfigtrial-f912f',
    storageBucket: 'remoteconfigtrial-f912f.appspot.com',
    iosBundleId: 'com.example.firebaseRemoteConfigApp.RunnerTests',
  );
}
